plugins:
  rsm:
    executor: central_deployment_agent
    package_name: cloudify_resource_management
    source: https://github.com/Cloudify-PS/cloudify-rms-plugin/archive/master.zip
    package_version: '0.0.2'

node_types:
  cloudify.nodes.resource_management.Usage:
    derived_from: cloudify.nodes.Root
    properties:
      system_name:
        type: string
        required: true
        description: >
          Name of system which is owning this kind of resource.
          Name 'system' is general because it may be e.g.
          VIM (like Openstack), NMS / EMS or even single device.
          This name should be used to assign given resource type
          to some top level category.
      resource_name:
        type: string
        required: false
        description: >
          Name of resource which will be used as identifier
          e.g. 'security_group' or 'floating_ip'
          for 'openstack' system_name
      scope:
        type: string
        default: 'project'
        description: >
          project - it means that 'list' operation for this resource type
          it returning items only for single tenant / project / subpart of the system
          global - it means that 'list' operation for this resource type
          it returning items from whole system
      operation_inputs:
        default: {}
      runtime_property_name:
        type: string
        default: 'usage'
    interfaces:
      cloudify.interfaces.operations:
        list: #list instances of given resource
          implementation: ~

  cloudify.nodes.resource_management.Quota:
    derived_from: cloudify.nodes.Root
    properties:
      system_name:
        type: string
        required: true
        description: >
          Name of system which is owning this kind of resource.
          Name 'system' is general because it may be e.g.
          VIM (like Openstack), NMS / EMS or even single device.
          This name should be used to assign given resource type
          to some top level category.
      resource_name:
        type: string
        required: false
        description: >
          Name of resource which will be used as identifier
          e.g. 'security_group' or 'floating_ip' for 'openstack' system_name
          If empty it means that Qouta node can collect qouta for multiple resources
      scope:
        type: string
        required: true
        default: 'project'
        description: >
          project - it means that this node_template is able to
          manage qouta for all resource types in one of system projects
          global - it means that this node_template is able
          to manage qouta for all resource types in system
      runtime_property_name:
        type: string
        default: 'quota'
    interfaces:
      cloudify.interfaces.lifecycle:
        create: #create or get qouta
          implementation: ~
        update: #updates qouta
          implementation: ~

  cloudify.nodes.resource_management.Project:
    derived_from: cloudify.nodes.Root
    properties:
      project_name:
        type: string
        description: >
          Name of project
          It will be used only as label for resources usage data structure
      deployment_id:
        type: string
        description: >
          Deployment ID for deployment created from project blueprint
          It should be already installed

  cloudify.nodes.resource_management.Result:
    derived_from: cloudify.nodes.Root

workflows:
  calculate_resources_availability:
    mapping: rsm.resource_management_plugin.tasks.calculate_resources_availability
    parameters:
      mode:
        type: string
        required: false
        default: 'simple'
        description: >
          simple - all executions of list workflow will be executed sequentially
          parallel - executions of list workflow will be executed in parallel

  check_resources_availability:
    mapping: rsm.resource_management_plugin.tasks.check_resources_availability
    parameters:
      project_id:
        type: string
        required: true
        description: >
          Identifier of project, for which resource profile should be validated
      profile_name:
        type: string
        required: false
        default: ~
        description: >
          Name of secret from secret store which is containing resource profiles
          definition as "JSON string"
      profile_str:
        type: string
        required: false
        default: ~
        description: >
          Dict containing resource profile definition.
          It may be used when you would like to pass profile definiction directly
          without using secret store.
      mode:
        type: string
        required: false
        default: 'simple'
        description: >
          simple - all executions of list workflow will be executed sequentially
          parallel - executions of list workflow will be executed in parallel

  execute_conditionally:
    mapping: rsm.resource_management_plugin.tasks.execute_conditionally
    parameters:
      execution_dict:
        required: true
        description: >
          Dictionary describes execution compliant with Cloudify Manager REST API executions start operation.
          Should contains such fields:
          deployment_id - mandatory
          workflow_id - mandatory
          allow_custom_parameters - optional
          parameters - optional
          force - optional
      project_id:
        type: string
        required: true
        description: >
          Identifier of project, for which resource profile should be validated
      profile_name:
        type: string
        required: false
        default: ~
        description: >
          Name of secret from secret store which is containing resource profiles
          definition as "JSON string"
      profile_str:
        type: string
        required: false
        default: ~
        description: >
          Dict containing resource profile definition.
          It may be used when you would like to pass profile definiction directly
          without using secret store.
      mode:
        type: string
        required: false
        default: 'simple'
        description: >
          simple - all executions of list workflow will be executed sequentially
          parallel - executions of list workflow will be executed in parallel