pluings:

  resources:
    executor: central_deployment_agent
    package_name: cloudify_resources
    source: https://github.com/Cloudify-PS/cloudify-rms-plugin/archive/master.zip
    package_version: '0.0.1'
